apiVersion: apps/v1
kind: Deployment
metadata:
 name: mysql
spec:
 strategy:
   rollingUpdate:
     maxSurge: 1
     maxUnavailable: 1
   type: RollingUpdate
 replicas: 1
 selector:
   matchLabels:
     app: mysql
 template:
   metadata:
     labels:
       app: mysql
   spec:
     containers:
       - name: mysql
         image: mysql:8
         resources:
          requests:
            cpu: "0.2"
            memory: "200Mi"
         ports:
           - containerPort: 3306
             name: mysql
         env:
           - name: MYSQL_ROOT_PASSWORD
             value: marko6462
           - name: MYSQL_DATABASE
             value: AJAX_CURR
         volumeMounts:
           - mountPath: /var/lib/mysql
             name: mysql-persistent-storage
     volumes:
       - name: mysql-persistent-storage
         persistentVolumeClaim:
           claimName: mysql-pv
---
# Define a 'Service' To Expose mysql to Other Services
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None