apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv
spec:
  storageClassName: standard #storage class provided by GCP
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  